In [137]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression

In [138]:
df = pd.read_csv("diabetes.csv")
df

Pregnancies  Glucose  ...  Age  Outcome
0              6      148  ...   50        1
1              1       85  ...   31        0
2              8      183  ...   32        1
3              1       89  ...   21        0
4              0      137  ...   33        1
..           ...      ...  ...  ...      ...
763           10      101  ...   63        0
764            2      122  ...   27        0
765            5      121  ...   30        0
766            1      126  ...   47        1
767            1       93  ...   23        0

[768 rows x 9 columns]

In [154]:
df.describe()

Pregnancies     Glucose  ...         Age     Outcome
count   768.000000  768.000000  ...  768.000000  768.000000
mean      3.845052  120.894531  ...   33.240885    0.348958
std       3.369578   31.972618  ...   11.760232    0.476951
min       0.000000    0.000000  ...   21.000000    0.000000
25%       1.000000   99.000000  ...   24.000000    0.000000
50%       3.000000  117.000000  ...   29.000000    0.000000
75%       6.000000  140.250000  ...   41.000000    1.000000
max      17.000000  199.000000  ...   81.000000    1.000000

[8 rows x 9 columns]

In [139]:
x = df[["Pregnancies",	"Glucose",	"BloodPressure",	"SkinThickness",	"Insulin",	"BMI",	"DiabetesPedigreeFunction","Age"]].values
x

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [140]:
y = df["Outcome"].values
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [141]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.1, random_state = 0)
x_train

array([[6.00e+00, 1.54e+02, 7.40e+01, ..., 2.93e+01, 8.39e-01, 3.90e+01],
       [4.00e+00, 8.30e+01, 8.60e+01, ..., 2.93e+01, 3.17e-01, 3.40e+01],
       [1.00e+00, 9.70e+01, 7.00e+01, ..., 3.81e+01, 2.18e-01, 3.00e+01],
       ...,
       [4.00e+00, 9.40e+01, 6.50e+01, ..., 2.47e+01, 1.48e-01, 2.10e+01],
       [1.10e+01, 8.50e+01, 7.40e+01, ..., 3.01e+01, 3.00e-01, 3.50e+01],
       [5.00e+00, 1.36e+02, 8.20e+01, ..., 0.00e+00, 6.40e-01, 6.90e+01]])

In [142]:
x_test

array([[1.000e+00, 1.990e+02, 7.600e+01, 4.300e+01, 0.000e+00, 4.290e+01,
        1.394e+00, 2.200e+01],
       [2.000e+00, 1.070e+02, 7.400e+01, 3.000e+01, 1.000e+02, 3.360e+01,
        4.040e-01, 2.300e+01],
       [4.000e+00, 7.600e+01, 6.200e+01, 0.000e+00, 0.000e+00, 3.400e+01,
        3.910e-01, 2.500e+01],
       [5.000e+00, 1.660e+02, 7.200e+01, 1.900e+01, 1.750e+02, 2.580e+01,
        5.870e-01, 5.100e+01],
       [0.000e+00, 1.110e+02, 6.500e+01, 0.000e+00, 0.000e+00, 2.460e+01,
        6.600e-01, 3.100e+01],
       [1.000e+00, 8.100e+01, 7.200e+01, 1.800e+01, 4.000e+01, 2.660e+01,
        2.830e-01, 2.400e+01],
       [9.000e+00, 1.520e+02, 7.800e+01, 3.400e+01, 1.710e+02, 3.420e+01,
        8.930e-01, 3.300e+01],
       [3.000e+00, 1.760e+02, 8.600e+01, 2.700e+01, 1.560e+02, 3.330e+01,
        1.154e+00, 5.200e+01],
       [2.000e+00, 1.270e+02, 5.800e+01, 2.400e+01, 2.750e+02, 2.770e+01,
        1.600e+00, 2.500e+01],
       [6.000e+00, 1.030e+02, 7.200e+01, 3.200e+01, 1.9

Feature Scaling

In [143]:
from sklearn.preprocessing import StandardScaler

In [144]:
sc = StandardScaler()

In [145]:
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [146]:
x_train

array([[ 0.64073703,  1.06850378,  0.24780543, ..., -0.3557498 ,
         1.13806722,  0.47594352],
       [ 0.04843029, -1.20025169,  0.87103945, ..., -0.3557498 ,
        -0.45291915,  0.05473838],
       [-0.84002981, -0.75289146,  0.04006075, ...,  0.76504362,
        -0.75465795, -0.28222573],
       ...,
       [ 0.04843029, -0.84875436, -0.2196201 , ..., -0.94161909,
        -0.96800861, -1.04039498],
       [ 2.12150386, -1.13634308,  0.24780543, ..., -0.25385949,
        -0.50473289,  0.13897941],
       [ 0.34458366,  0.49332633,  0.66329478, ..., -4.08748243,
         0.53154176,  3.00317435]])

In [147]:
x_test

array([[-8.90267381e-01,  2.01919271e+00,  3.98232563e-01,
         1.50781181e+00, -6.77151530e-01,  1.46436736e+00,
         2.45930357e+00, -9.69409076e-01],
       [-5.85598099e-01, -4.53829621e-01,  2.98674422e-01,
         6.71623654e-01,  3.44613467e-01,  3.11262602e-01,
        -3.52730856e-01, -8.74922368e-01],
       [ 2.37404635e-02, -1.28713063e+00, -2.98674422e-01,
        -1.25804132e+00, -6.77151530e-01,  3.60858505e-01,
        -3.89656561e-01, -6.85948954e-01],
       [ 3.28409745e-01,  1.13213036e+00,  1.99116281e-01,
        -3.59201705e-02,  1.11093721e+00, -6.55857515e-01,
         1.67069446e-01,  1.77070544e+00],
       [-1.19493666e+00, -3.46306911e-01, -1.49337211e-01,
        -1.25804132e+00, -6.77151530e-01, -8.04645225e-01,
         3.74421480e-01, -1.19028709e-01],
       [-8.90267381e-01, -1.15272724e+00,  1.99116281e-01,
        -1.00242336e-01, -2.68445531e-01, -5.56665708e-01,
        -6.96423952e-01, -7.80435661e-01],
       [ 1.54708687e+00,  7.558008

Logistic Regression


In [148]:
classifier = LogisticRegression()
classifier.fit(x_train, y_train)

pred_y = classifier.predict(x_test)

In [149]:
pred_y

array([1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0])

Checking Accuracy

In [150]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,pred_y)

0.8571428571428571

Confusion Matrix

In [151]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,pred_y)

array([[48,  3],
       [ 8, 18]])

Now taking a random person's information to see if they have diabetes

In [152]:
#random person 1
classifier.predict(sc.transform([[0,	137,	40,	35,	168,	43.1,	2.288,	33	]]))

array([1])

In [153]:
#random person 2
classifier.predict(sc.transform([[1,89,66,23,94,28.1,0.167,21]]))	

array([0])